### ISSUE TITLE
Provide full EFI folder.

### ISSUE THREAD

**Issue by c-orter** [1Revenger1/X1-Extreme-OpenCore-Resources#1]
Whoops, sorry for spazzing out. I was wondering if it would be possible for you to provide your full EFI folder, even just as a zip in this issue. I am having a hard time getting my system to boot with opencore and was hoping I'd be able to glean something from your EFI.

Thanks!

**Comment by c8r821** [comment]
Whoops, sorry for spazzing out. I was wondering if it would be possible for you to provide your full EFI folder, even just as a zip in this issue. I am having a hard time getting my system to boot with opencore and was hoping I'd be able to glean something from your EFI.

Thanks!

**Comment by averycblack** [comment]
No, I could probably drop in the USBMap kext though since that's specific to the laptop.
There are licenses for the kexts to deal with and other stuff to deal with. And also, I don't want this to just be something to copy and paste - I'd rather you go through a guide and learn. i.e. @khronokernel opencore guide.

If your struggling with something in particular, I don't mind helping out here or on the /r/Hackintosh discord server

**Comment by c-orter** [comment]
The USBMap might be immensely helpful, the issue I'm running into is specifically documented in the vanilla opencore guide ([stop sign and garbled text](https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/troubleshooting/troubleshooting#stop-sign-with-corrupted-text-still-waiting-for-root-device)) but I've tried setting XhciPortLimit to true and no dice.

**Comment by averycblack** [comment]
alright, give me like 30 minutes - I've got some ACPI edits I want to test as well before uploading

**Comment by c-orter** [comment]
Take your time. I appreciate the help!

**Comment by averycblack** [comment]
Should be good now - check latest master
